# Default values for Tanzu Observability Demo App
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 
  blue: 1
  green: 1

namespace: "observability-system"

cluster: otel-test-gke-cluster-021323

image:
  repository: projects.registry.vmware.com/tanzu_observability_keights_saas/vanilla-demo-app/
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

wavefront:
   token: "your API token"
   url: "https://your_cluster.wavefront.com/api/"

logs:
  enabled: true

customtags:
   location: k8s-cluster
   environment: dev

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

